---
title: "Clinical Survival summary"
output:
  html_document: default
  word_document: default
date: "2023-11-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(gtsummary)
library(openxlsx)
```

# Data

```{r}
dataset<- readRDS("/work/users/x/l/xlpeng/yehseq_decaf_freeze/yehseq_pdac_pi.decaf_freeze.rds")
```

# Clinical

```{r}
clinicalDat <- dataset$clinicalDat
```

# Basic Cleaning

Change capitals and make words uniform.

```{r}
clinicalDat$race<-ifelse(clinicalDat$race=="white","White",clinicalDat$race)

clinicalDat$tobacco_former_current_never<-ifelse(clinicalDat$tobacco_former_current_never=="current","Current", ifelse(clinicalDat$tobacco_former_current_never=="former","Former", ifelse(clinicalDat$tobacco_former_current_never=="never","Never",clinicalDat$tobacco_former_current_never)))

clinicalDat$alcohol_yn<-ifelse(clinicalDat$alcohol_yn=="no","No",clinicalDat$alcohol_yn)

clinicalDat$drugs<-ifelse(clinicalDat$drugs=="no"|clinicalDat$drugs=="None","No",clinicalDat$drugs)

clinicalDat$preop_diabetes_yes_recent_no<-ifelse(clinicalDat$preop_diabetes_yes_recent_no=="no"| clinicalDat$preop_diabetes_yes_recent_no=="NO","No", ifelse(clinicalDat$preop_diabetes_yes_recent_no=="yes","Yes",clinicalDat$preop_diabetes_yes_recent_no))

clinicalDat$bileduct_stent_clean<-ifelse(clinicalDat$bileduct_stent_clean=="no","No", ifelse(clinicalDat$bileduct_stent_clean=="yes","Yes",clinicalDat$bileduct_stent_clean))

clinicalDat$preop_cholangitis_yn <-ifelse(clinicalDat$preop_cholangitis_yn=="no","No",clinicalDat$preop_cholangitis_yn)

clinicalDat$chronic_pancreatitis_yn<-ifelse(clinicalDat$chronic_pancreatitis_yn=="no","No", ifelse(clinicalDat$chronic_pancreatitis_yn=="yes","Yes",clinicalDat$chronic_pancreatitis_yn))

clinicalDat$Recent.ABX<-ifelse(clinicalDat$Recent.ABX=="no","No", ifelse(clinicalDat$Recent.ABX=="yes","Yes",clinicalDat$Recent.ABX))

clinicalDat$tumor_location<-ifelse(clinicalDat$tumor_location=="head","Head", ifelse(clinicalDat$tumor_location=="tail","Tail",clinicalDat$tumor_location))

clinicalDat$Lymphovascular.Invasion<-ifelse(clinicalDat$Lymphovascular.Invasion=="no","No", ifelse(clinicalDat$Lymphovascular.Invasion=="yes","Yes",clinicalDat$Lymphovascular.Invasion))

clinicalDat$PNI<-ifelse(clinicalDat$PNI==" Yes"|clinicalDat$PNI=="yes","Yes",ifelse(clinicalDat$PNI=="no","No",clinicalDat$PNI))

clinicalDat$`Margin.(close.<1mm)`<-ifelse(clinicalDat$`Margin.(close.<1mm)`=="Close ","Close", ifelse(clinicalDat$`Margin.(close.<1mm)`=="positive","Positive",clinicalDat$`Margin.(close.<1mm)`))

clinicalDat$Neoadj.Tx<-ifelse(clinicalDat$Neoadj.Tx=="no","No",clinicalDat$Neoadj.Tx)

clinicalDat$neo_folfirinox<-ifelse(clinicalDat$neo_folfirinox=="no","No",clinicalDat$neo_folfirinox)
 
clinicalDat$neo_gem<-ifelse(clinicalDat$neo_gem=="yes","Yes",clinicalDat$neo_gem)

clinicalDat$neo_xrt<-ifelse(clinicalDat$neo_xrt=="no","No",clinicalDat$neo_xrt)

clinicalDat$`preop.RT.(for.adeno.only)`<-ifelse(clinicalDat$`preop.RT.(for.adeno.only)`=="no","No",clinicalDat$`preop.RT.(for.adeno.only)`)

clinicalDat$`Adj.Tx.(Yes.if.got.any.treatment.for.PDAC)`<-ifelse(clinicalDat$`Adj.Tx.(Yes.if.got.any.treatment.for.PDAC)`=="no" ,"No", ifelse(clinicalDat$`Adj.Tx.(Yes.if.got.any.treatment.for.PDAC)`=="yes","Yes", clinicalDat$`Adj.Tx.(Yes.if.got.any.treatment.for.PDAC)`))

clinicalDat$Adj_Tx<-ifelse(clinicalDat$Adj_Tx=="no","No",ifelse(clinicalDat$Adj_Tx=="No ","No",ifelse(clinicalDat$Adj_Tx=="yes","Yes",clinicalDat$Adj_Tx)))
 
clinicalDat$Adjuvant.XRT<-ifelse(clinicalDat$Adjuvant.XRT=="no","No", ifelse(clinicalDat$Adjuvant.XRT=="yes","Yes",clinicalDat$Adjuvant.XRT))

clinicalDat$`Recur.(NA.if.non-PDAC.or.non-resectable.disease,.even.if.treated.for.other.causes)`<-ifelse(clinicalDat$`Recur.(NA.if.non-PDAC.or.non-resectable.disease,.even.if.treated.for.other.causes)`=="no","No",ifelse(clinicalDat$`Recur.(NA.if.non-PDAC.or.non-resectable.disease,.even.if.treated.for.other.causes)`=="yes","Yes",clinicalDat$`Recur.(NA.if.non-PDAC.or.non-resectable.disease,.even.if.treated.for.other.causes)`))


clinicalDat$Race<-ifelse(clinicalDat$Race=="black","Black",ifelse(clinicalDat$Race=="white"|clinicalDat$Race=="white ","White", clinicalDat$Race))
 
clinicalDat$operation <- ifelse(clinicalDat$operation=="whipple","Whipple",clinicalDat$operation)

clinicalDat$neo_reg_clean <-ifelse(clinicalDat$neo_reg_clean=="none","None",clinicalDat$neo_reg_clean)

clinicalDat$Path.Response<-ifelse(clinicalDat$Path.Response=="Parital","Partial",clinicalDat$Path.Response)

clinicalDat$Recur.Site <- gsub("[\\\\\"]", "", clinicalDat$Recur.Site)

clinicalDat$Recur.Met.Chemo.Tolerance<-ifelse(clinicalDat$Recur.Met.Chemo.Tolerance=="not tolerated ","not tolerated",clinicalDat$Recur.Met.Chemo.Tolerance)

clinicalDat$Genetic.Mutation<-ifelse(clinicalDat$Genetic.Mutation=="none","None",clinicalDat$Genetic.Mutation)

clinicalDat$Genetic.Test.Company<-ifelse(clinicalDat$Genetic.Test.Company=="FoundationOne","Foundation One",ifelse(clinicalDat$Genetic.Test.Company=="invitae "|clinicalDat$Genetic.Test.Company=="invitae"|clinicalDat$Genetic.Test.Company=="INVITAE","Invitae",ifelse(clinicalDat$Genetic.Test.Company=="strata "|clinicalDat$Genetic.Test.Company=="STRATA","strata",clinicalDat$Genetic.Test.Company)))

clinicalDat$Primary.Language<-ifelse(clinicalDat$Primary.Language=="english"|clinicalDat$Primary.Language=="english "|clinicalDat$Primary.Language=="Enlgish","English",clinicalDat$Primary.Language)

 clinicalDat$`Insurance.(medicare,.medicaid,.private,.none)`<-ifelse(clinicalDat$`Insurance.(medicare,.medicaid,.private,.none)`=="medicare "|clinicalDat$`Insurance.(medicare,.medicaid,.private,.none)`=="medicare"|clinicalDat$`Insurance.(medicare,.medicaid,.private,.none)`=="Medicate","Medicare",ifelse(clinicalDat$`Insurance.(medicare,.medicaid,.private,.none)`=="no active insurance on file ","no active insurance on file",ifelse(clinicalDat$`Insurance.(medicare,.medicaid,.private,.none)`=="no insurance on file ","no insurance on file",ifelse(clinicalDat$`Insurance.(medicare,.medicaid,.private,.none)`=="private "|clinicalDat$`Insurance.(medicare,.medicaid,.private,.none)`=="private ","private",clinicalDat$`Insurance.(medicare,.medicaid,.private,.none)`))))

clinicalDat$social.support<-ifelse(clinicalDat$social.support=="married","Married",clinicalDat$social.support)

clinicalDat$`Adj.Chemo.(for.adeno.only)`<-ifelse(clinicalDat$`Adj.Chemo.(for.adeno.only)`=="no","No",ifelse(clinicalDat$`Adj.Chemo.(for.adeno.only)`=="yes","Yes",clinicalDat$`Adj.Chemo.(for.adeno.only)`))
 
 clinicalDat$`Adj.RT.(for.adeno.only)`<-ifelse(clinicalDat$`Adj.RT.(for.adeno.only)`=="no","No",ifelse(clinicalDat$`Adj.RT.(for.adeno.only)`=="yes","Yes",clinicalDat$`Adj.RT.(for.adeno.only)`))

 clinicalDat$`Adj.Systemic.(for.adeno.only)`<-ifelse(clinicalDat$`Adj.Systemic.(for.adeno.only)`=="no","No",ifelse(clinicalDat$`Adj.Systemic.(for.adeno.only)`=="yes","Yes", ifelse(clinicalDat$`Adj.Systemic.(for.adeno.only)`=="unknown","Unknown",clinicalDat$`Adj.Systemic.(for.adeno.only)`)))

 clinicalDat$`Adj.Chemo/RT.(for.adeno.only)`<-ifelse(clinicalDat$`Adj.Chemo/RT.(for.adeno.only)`=="no","No",ifelse(clinicalDat$`Adj.Chemo/RT.(for.adeno.only)`=="xeloda/RT","Xeloda/RT",ifelse(clinicalDat$`Adj.Chemo/RT.(for.adeno.only)`=="yes","Yes",clinicalDat$`Adj.Chemo/RT.(for.adeno.only)`)))
 
```

For preop_albumin changed "not found" "not recorded" to NA

For preop_ca199 changed "not found" "not recorded" or "not sent" to NA

```{r}
clinicalDat$preop_albumin<-ifelse(clinicalDat$preop_albumin=="not found"|clinicalDat$preop_albumin=="not recorded",NA,clinicalDat$preop_albumin)

clinicalDat$preop_ca199<-ifelse(clinicalDat$preop_ca199=="not found "|clinicalDat$preop_ca199=="not recorded"|clinicalDat$preop_ca199=="not sent",NA,clinicalDat$preop_ca199)

```

```{r}


tbl<-clinicalDat %>%  
    mutate_at(c("age","pre_op_cm","pre_op_bmi","preop_albumin","preop_ca199","Pos.LN","RFS.(Op.date.to.radiographic.recurrence)") , as.numeric) %>%
 tbl_summary(missing_text = "NA",statistic = list(
      all_continuous() ~ "{median} ({min},{max})",
      all_categorical() ~ "{n} ({p}%)"),
      type = list(c(alcohol_yn,bileduct_stent_clean,preop_cholangitis_yn,chronic_pancreatitis_yn,Recent.ABX,Neoadj.Tx,`Recur.(NA.if.non-PDAC.or.non-resectable.disease,.even.if.treated.for.other.causes)`) ~ "categorical"
    )) %>% add_n() %>% modify_footnote(n = "N") %>% bold_labels() %>% as_gt() %>% gt::gtsave("/work/users/a/r/arthih/Laura_Clinical_Parsing/ClinicalDat_cleaned_summary_112023.html")

tbl_df <- tbl %>% as.data.frame()

tbl %>% as.data.frame() %>% write.xlsx("Clinical_columns_N_summary_112023.xlsx")

```


```{r}

tbl_freetxt <- clinicalDat %>%  select(tobacco_freetxt,alcohol_freetxt, personal_hx_ca, fam_hx_ca, biliaryStent, preop_cholangitis, recent_abx.free.text, Date.of.Surgery, Date.of.Dx, Final.Date, Final.Status.Source, Margin.Free.Text,  Neoadj.Regimen,`Neo.(Cycles)`, Neo.Tolerance,Path.Response,RECIST.Response,`Adj.Time/Cycless`, Adj.Regimen, RT.details, `Adj.Time/Cycles`, Adj.Tolerance, Recur.Date, Recur.Site, `Recur/Met.Chemo.Time/Cycles`, Recur.Met.Chemo.Tolerance,MSI, Genetic.Mutation, Date.Test.Sent, Genetic.Test.Company, Genetic.Testing.or.Genetics.Referral, last_review, schmidt_flag, Schmidt.Flag, sample_id, `Notes/Other.health.problems`,Zip.Code,singlecell_library,singlecell_flowcell,rnaseq_runname,rna_seq_lib_id,ff_rnaseq_sample_id,patient_id,uniqID,) %>%
   tbl_summary(missing_text = "NA",statistic = list(
      all_continuous() ~ "{median} ({sd})",
      all_categorical() ~ "{n} ({p}%)"
    )) %>% add_n() %>% modify_footnote(n = "N") %>% bold_labels()

free_txt_N<-na.omit(data.frame(variable=tbl_freetxt$table_body$variable,n=tbl_freetxt$table_body$n))

```

```{r}

all_NAs <- dataset$clinicalDat %>% select_if(~ all(is.na(.))) %>% colnames()

NA_df<- data.frame(column_name = all_NAs, column_number = which(colnames(dataset$clinicalDat) %in% all_NAs))

```

```{r}
# Create an Excel workbook
wb <- createWorkbook()

addWorksheet(wb, sheetName = "Categorical/Continuous")
writeDataTable(wb, sheet = 1, x = tbl_df)

addWorksheet(wb, sheetName = "Free-text")
writeDataTable(wb, sheet = 2, x = free_txt_N)

addWorksheet(wb, sheetName = "Only NAs")
writeDataTable(wb, sheet = 3, x = NA_df)

saveWorkbook(wb, "Clinical_variables_N_final_110923.xlsx")
```


```{r eval=FALSE}

type = list(c(age,pre_op_kg, pre_op_cm, pre_op_bmi,tobacco_py,preop_albumin,preop_ca199,`Overall.Survival.(diagnosis.to.death.in.months)`,`Recurrence.Event.(0=NED.1=radiographic.recurrence,.2.=.documented.chemical.recurrence.alone,.500=died.of.operation,.600.=.died.of.documented.non-PDAC.event.with.NED.900=unable.to.determine.due.to.lack.of.reccords,.950=unable.to.determine.due.to.indeterminate.imaging.990.=.non-resected.PDAC.case,.999=non-PDAC.case)`,`Overall.Survival.(OR.until.death)`,`Tumor.size.(path.report,.cm)`,Pos.LN,T.LN,`RFS-DOS`,`RFS.(Op.date.to.radiographic.recurrence)`)~'continuous',c(race,sex,preop_diabetes_yes_recent_no,alcohol_yn,tobacco_former_current_never,drugs,bileduct_stent_clean,preop_ecog,preop_cholangitis_yn,chronic_pancreatitis_yn,Recent.ABX,preop_diagnosis,tumor_location,operation,`Location/Procedure`,Surgeon,Last.Event,Path,Differentiation,`Differentiation.(mod,.poor)`,differentiation_clean,`T`,N,M,Lymphovascular.Invasion,PNI,`Margin.(close.<1mm)`,Stage,Neoadj.Tx,neo_folfirinox,neo_gem,neo_xrt,neo_other,neo_reg_clean,`preop.RT.(for.adeno.only)`,`preop.Chemo.(for.adeno.only)`,Path.Response.score,`Adj.Tx.(Yes.if.got.any.treatment.for.PDAC)`,`Adj.Chemo.(for.adeno.only)`,Adj_Tx,Adjuvant_Regimen_Clean,`Adj.Systemic.(for.adeno.only)`,Adjuvant.XRT,`Adj.Chemo/RT.(for.adeno.only)`,`Adj.RT.(for.adeno.only)`,`Recur.(NA.if.non-PDAC.or.non-resectable.disease,.even.if.treated.for.other.causes)`,`Recurrence.Event.(0=NED.1=radiographic.recurrence,.2.=.documented.chemical.recurrence.alone,.500=died.of.operation,.600.=.died.of.documented.non-PDAC.event.with.NED.900=unable.to.determine.due.to.lack.of.reccords,.950=unable.to.determine.due.to.indeterminate.imaging.990.=.non-resected.PDAC.case,.999=non-PDAC.case)`,KRAS.mutation.status,Primary.Language,social.support,`Insurance.(medicare,.medicaid,.private,.none)`,Race,normal_or_tumor,data_type,R,)~'categorical')

```

